### ISSUE TITLE
Deploy daemon in frozen state

### ISSUE THREAD

**Issue by j-boivie** [fiaas/fiaas-deploy-daemon#19]
We've had a deploy daemon that somehow ended up in a state where it appeared frozen, not triggering new deployments. Checking `kubectl logs` for the fdd pod just showed the last succcessful deployment after which the pod seemingly stopped logging alltogether.

```
[2019-08-02 14:20:16,637|   INFO] Saving result SUCCESS for my_service deployment_id=679a8b83-6476-4eef-9019-9fd51c56b4dc [fiaas_deploy_daemon.crd.status|Scheduler]
 ```
After restarting the fdd pod deployments resumed normally.

**Comment by mortenlj** [comment]
I don't think there is enough information to go on here, but we can try to collect more information in this issue if it happens again.

The changes in #16 should help gather more information, we just need to get that released into a stable version. That will probably happen this week.

Once that is in place, sending a SIGUSR2 to the process will dump some thread information to the log, so we can hopefully see where it is stuck. It will also be useful to get any related k8s events, so if you can collect the output of `kubectl describe pod` as well that would be very useful.

**Comment by j-boivie** [comment]
We just had seemingly the same thing happen again, here is the output of `kubectl describe pod <my-fdd-pod>`, unfortunately no events are present:

```yaml
Name:               fiaas-deploy-daemon-666f9c6bb6-9wzlp
Namespace:          my-namespace
Priority:           0
PriorityClassName:  <none>
Node:               ip-10-34-0-91.eu-west-1.compute.internal/10.34.0.91
Start Time:         Wed, 14 Aug 2019 10:52:57 +0200
Labels:             app=fiaas-deploy-daemon
                    fiaas/deployed_by=20190812124040-967aba3
                    fiaas/deployment_id=93100463-c7cb-4098-9275-e714bacabf20
                    fiaas/status=active
                    fiaas/version=20190812124040-967aba3
                    pod-template-hash=666f9c6bb6
Annotations:        prometheus.io/path: /internal-backstage/prometheus
                    prometheus.io/port: 5000
                    prometheus.io/scrape: true
Status:             Running
IP:                 10.34.0.71
Controlled By:      ReplicaSet/fiaas-deploy-daemon-666f9c6bb6
Containers:
  fiaas-deploy-daemon:
    Container ID:   docker://ed98112f917f255d6c2965afbefe64329624036aae139a2c58cd984cb36b4250
    Image:          fiaas/fiaas-deploy-daemon:20190812124040-967aba3
    Image ID:       docker-pullable://fiaas/fiaas-deploy-daemon@sha256:bd10b42f844bb7d96448448322796df20bbddfa45f79899a805addc669805fdd
    Port:           5000/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 14 Aug 2019 10:52:59 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     250m
      memory:  128Mi
    Requests:
      cpu:      250m
      memory:   128Mi
    Liveness:   http-get http://:http/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:http/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment Variables from:
      fiaas-deploy-daemon  ConfigMap  Optional: true
    Environment:
      ARTIFACT_NAME:          fiaas-deploy-daemon
      CLUSTER_NAME:           etech-collaboration-eks-dev
      CONSTRETTO_TAGS:        kubernetes-pro,kubernetes,pro
      FIAAS_CLUSTER_NAME:     etech-collaboration-eks-dev
      FIAAS_ENVIRONMENT:      pro
      FIAAS_INFRASTRUCTURE:   diy
      FIAAS_LIMITS_CPU:       1 (limits.cpu)
      FIAAS_LIMITS_MEMORY:    134217728 (limits.memory)
      FIAAS_NAMESPACE:        etech-collaboration-dev (v1:metadata.namespace)
      FIAAS_POD_NAME:         fiaas-deploy-daemon-666f9c6bb6-9wzlp (v1:metadata.name)
      FIAAS_REQUESTS_CPU:     1 (requests.cpu)
      FIAAS_REQUESTS_MEMORY:  134217728 (requests.memory)
      FINN_ENV:               pro
      IMAGE:                  fiaas/fiaas-deploy-daemon:20190812124040-967aba3
      LOG_FORMAT:             plain
      LOG_STDOUT:             true
      VERSION:                20190812124040-967aba3
    Mounts:
      /tmp from tmp (rw)
      /var/run/config/fiaas/ from fiaas-deploy-daemon-config (ro)
      /var/run/secrets/fiaas/ from fiaas-deploy-daemon-secret (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-rbdzn (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  fiaas-deploy-daemon-secret:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  fiaas-deploy-daemon
    Optional:    true
  fiaas-deploy-daemon-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      fiaas-deploy-daemon
    Optional:  true
  tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  default-token-rbdzn:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-rbdzn
    Optional:    false
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```

When the change mentioned is deployed, how do I go about sending the signal to the FDD-process? From the node the pod is running on?
